baseURL = "https://test.inksandpens.com/"
languageCode = "en-us"
title = "Inks and Pens"
theme = "dgraph"

author = "Felix Jen"
paginate = 5

copyright = "Copyright (c) 2013-2018, Felix Jen; all rights reserved."
