baseURL = "https://www.inksandpens.com"
languageCode = "en-us"
title = "Inks and Pens"
theme = "pixyll"

author = "Felix Jen"
enableEmoji = true
DefaultContentLanguage = "en"
disqus_shortname = "inkoutsidethebottle"

[params]
  paginate = 8
#  google_analytics_id = "UA-118000647-1"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

copyright = "Copyright (c) 2013-2018, Felix Jen; all rights reserved."
