baseURL = "https://www.inksandpens.com"
languageCode = "en-us"
title = "Inks and Pens"
theme = "pixyll"

author = "Felix Jen"
enableEmoji = true
DefaultContentLanguage = "en"
disqusShortname = "inkoutsidethebottle"

copyright = "Copyright (c) 2013-2018, Felix Jen; all rights reserved."


[params]
  paginate = 8
#  google_analytics_id = "UA-118000647-1"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "image"]
params = [""]

[outputs]
home = ["HTML", "RSS", "Algolia"]

