backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads" # Storage for media files
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Author", name: "author", widget: "string", default: "Felix Jen"}
      - {label: "image", name: "image", widget: "string", required: false}
      - {label: "Required Libraries", name: "require", widget: "list", required: false}
      - {label: "Table of Contents", name: "toc", widget: "boolean", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}